#ifndef NEOLAMP_MODES_H
#define NEOLAMP_MODES_H

#define STATE_SLEEPING 0
#define STATE_WAKEUP 1
#define STATE_DAYTIME 2

enum LampMode {
    LAMP_MODE_RED = 0,
    LAMP_MODE_ORANGE,
    LAMP_MODE_YELLOW,
    LAMP_MODE_LIGHT_GREEN,
    LAMP_MODE_GREEN,
    LAMP_MODE_TURQUOISE,
    LAMP_MODE_BLUE,
    LAMP_MODE_PURPLE,
    LAMP_MODE_MAGENTA,
    LAMP_MODE_WHITE,
    LAMP_MODE_MIX,
    LAMP_MODE_CIRCLE,
    LAMP_MODE_CIRCLE_FILLED,
    LAMP_MODE_RAINBOW,
    LAMP_MODE_COUNT = 14
};

#define MODE_COLOR_RED "red"
#define MODE_COLOR_ORANGE "orange"
#define MODE_COLOR_YELLOW "yellow"
#define MODE_COLOR_LIGHT_GREEN "light_green"
#define MODE_COLOR_GREEN "green"
#define MODE_COLOR_TURQUOISE "turquoise"
#define MODE_COLOR_BLUE "blue"
#define MODE_COLOR_PURPLE "purple"
#define MODE_COLOR_MAGENTA "magenta"
#define MODE_COLOR_WHITE "white"
#define MODE_COLOR_MIX "mix"
#define MODE_COLOR_PULSE "pulse"
#define MODE_COLOR_CIRCLE "circle"
#define MODE_COLOR_CIRCLE_FILLED "circle_filled"
#define MODE_COLOR_RAINBOW "rainbow"

#define STATE_ANIMATION_MIX MODE_COLOR_MIX
#define STATE_ANIMATION_PULSE MODE_COLOR_PULSE
#define STATE_ANIMATION_CIRCLE MODE_COLOR_CIRCLE
#define STATE_ANIMATION_CIRCLE_FILLED MODE_COLOR_CIRCLE_FILLED
#define STATE_ANIMATION_RAINBOW MODE_COLOR_RAINBOW
#define STATE_ANIMATION_PICK "pick"
#define STATE_ANIMATION_GREEN MODE_COLOR_GREEN
#define STATE_ANIMATION_RED MODE_COLOR_RED
#define STATE_ANIMATION_OFF "off"

#define MODE_COUNT LAMP_MODE_COUNT

#endif
